# Generated by Django 5.0.3 on 2024-04-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=111, max_length=20),
            preserve_default=False,
        ),
    ]
