# Generated by Django 5.0.3 on 2024-03-20 02:02

import django.db.models.deletion
import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(verbose_name=users.models.validate_date)),
                ('profilePicture', models.ImageField(upload_to='images/profilePictures')),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('document', models.ImageField(upload_to='images/documents')),
                ('selfie', models.ImageField(upload_to='images/selfies')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
