# Generated by Django 5.0.3 on 2024-05-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='demo',
        ),
    ]
