# Generated by Django 5.0.3 on 2024-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hobbies',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
